### ISSUE TITLE
Documentation plan about version 1.3

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela.io#562]
# Getting Started

# OAM Engine(Vela Core)

## Tutorials
- [ ] Deploy the across the cloud application.
- [ ] Deploy Kubernetes workloads to multiple clusters.
- [ ] Deploy differentiated applications in multiple clusters.

## How-To Guides

- [x] how to list your application history versions. #603
- [x] how to roll back your application at any time. #603
- [ ] how to deploy the existed deployment and service to other clusters.

# VelaUX

## Tutorials
- [x] SSO with GitHub or LDAP.

## How-To Guides
- [x] how to manage the projects. #597
- [x] how to manage the users. #597
- [x] how to manage the roles. #597
- [ ] how to manage the cloud provider.
- [ ] how to manage the helm repository.
- [x] how to manage the docker registry. #612 
- [ ] how to manage the SSO provider.

# Extension
- [ ] how to create a private addon registry.

# References
